name: flim
description: minimal data-driven sprite render and animation lib for Flutter
version: 1.0.0
homepage: https://github.com/erf/flim

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  asset_cache: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
