name: flim
description: Minimal data-driven sprite render and animation lib for Flutter.
version: 0.3.1
homepage: https://github.com/erf/flim

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  asset_cache: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
